server:
  port: 8082 
spring:
  application:
    name: product-service
  datasource:
    # IMPORTANT: Nayi service, naya database. Dono ko mix nahi karna.
    url: jdbc:mysql://localhost:3306/ecom_product_db?createDatabaseIfNotExist=true
    username: root
    password: root  # <-- Apna asli MySQL password yahan daalna
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
